name: build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: sudo apt install python3-pip python3-cffi python3-brotli libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0
      - run: pip install mkdocs-material  
      - run: pip install mkdocs-include-markdown-plugin
      - run: pip install weasyprint
      - run: pip install mkpdfs-mkdocs
      - run: mkdocs gh-deploy --force --clean --verbose
